posConfig = {
	TEMPLATE_DASHBOARD_VERSION: 1.00,
	TEMPLATE_LOGIN_VERSION: 1.00,
        TEMPLATE_SIDEBAR_VERSION: 1.00,
        TEMPLATE_HEADER_VERSION: 1.00,
        TEMPLATE_LIST_INVOICE_VERSION: 1.00,
        TEMPLATE_ACCOUNT_VERSION: 1.00,
        TEMPLATE_LOGIN_VERSION: 1.00
};